apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    ksonnet.io/component: nfs-volume
  name: nfstest
  namespace: kubeflowteam3
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /
    server: 10.35.240.201
