apiVersion: storage.k8s.io/v1
kind: PersistentVolumeClaim
metadata:
  name: nfspvc2
  namespace: kubeflowteam3
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 102Gi
  storageClassName: manual
