apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ksonnet.io/component: nfs-volume
  name: nfspvc
  namespace: kubeflowteam3
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 70Gi
  storageClassName: manual
